---

- hosts: apache2
  remote_user: root
  roles:
    - hswong3i.apache2_vhosts

- hosts: mysql
  remote_user: root
  roles:
    - hswong3i.mysql_vhosts

- hosts: postgresql
  remote_user: root
  roles:
    - hswong3i.postgresql_vhosts

- hosts: bamboo
  remote_user: root
  roles:
    - hswong3i.bamboo
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw_to_port:
        - { to_port: "{{ bamboo_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ bamboo_server_port }}", proto: "tcp", rule: "allow" }
