---

- hosts: apache2
  remote_user: root
  roles:
    - hswong3i.apache2_vhosts

- hosts: mysql
  remote_user: root
  roles:
    - hswong3i.mysql_vhosts

- hosts: postgresql
  remote_user: root
  roles:
    - hswong3i.postgresql_vhosts

- hosts: crowd
  remote_user: root
  roles:
    - hswong3i.crowd
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw_to_port:
        - { to_port: "{{ crowd_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ crowd_server_port }}", proto: "tcp", rule: "allow" }
