---

- hosts: mysql
  remote_user: root
  roles:
    - hswong3i.mysql_vhosts

- hosts: postgresql
  remote_user: root
  roles:
    - hswong3i.postgresql_vhosts

- hosts: fisheye
  remote_user: root
  roles:
    - hswong3i.fisheye
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw_to_port:
        - { to_port: "{{ fisheye_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ fisheye_server_port }}", proto: "tcp", rule: "allow" }

- hosts: apache2
  remote_user: root
  roles:
    - hswong3i.apache2_vhosts
